{
  "branches": ["main", "next"],
  # "repositoryUrl": "https://base.sw.sbc.space/bitbucket/scm/~mkayander/versioning.git",
  # "tagFormat": "v${version}",

  "plugins": [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator",
      "@semantic-release/changelog",
      # "@semantic-release/npm",
      # "@semantic-release/github",
      ["@semantic-release/npm", { "npmPublish": false }],
    ],
}
