{
  "branches": ["main", "next"],
  # "repositoryUrl": "https://base.sw.sbc.space/bitbucket/scm/~mkayander/versioning.git",
  # "tagFormat": "v${version}",

  "plugins": [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator",
      ["@semantic-release/changelog", { "changelogFile": "docs/CHANGELOG.md" }],
      "@semantic-release/npm",
      [
        "@semantic-release/git",
        {
          "assets": ["dist/**/*.{js,css}", "docs", "package.json"],
          "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}",
        },
      ],
      [
        "@semantic-release/exec",
        {
          "successCmd": "node ./scripts/semrelSuccess.js ${nextRelease.version} ${nextRelease.notes} ${nextRelease.notes} ${options.branch} ${commits.length} ${Date.now()}",
        },
      ],
      # "@semantic-release/github",
      #       ["@semantic-release/npm", { "npmPublish": false }],
    ],
}
